# .pre-commit-config.yaml
# -----------------------------------------------------------------------------
# Pre-commit Configuration
#
# This file defines the set of hooks that are automatically run before commits.
# Hooks enforce code formatting, linting, and other checks to maintain code quality.
#
# Usage:
#   - Install pre-commit:      pip install pre-commit
#   - Install hooks:           pre-commit install
#   - Run manually on all:     pre-commit run --all-files
#
# Hooks included:
#   - black: Python formatter
#   - flake8: Linting
#   - end-of-file-fixer: Ensures newline at EOF
#   - trailing-whitespace: Removes trailing whitespace
#   - check-added-large-files: Prevents large file commits
# -----------------------------------------------------------------------------

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--check", "--diff"]
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--check-only", "--diff"]
        stages: [pre-commit]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--extend-ignore=E501,E203,E402,D202,I100,I101,I201,I202"]
        additional_dependencies:
          - flake8-bugbear
          - flake8-unused-arguments
          - flake8-import-order
          - flake8-comprehensions
          - flake8-simplify
          - flake8-eradicate
          - flake8-docstrings
        language_version: python3

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.11
    hooks:
      - id: vulture
        args: [nowplaying/, devtools/]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-setuptools]
        exclude: ^(tests/|setup\.py)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: ^testdata/
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
