[git]
conventional_commits = true
filter_unconventional = false

commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^doc", group = "Documentation" },
    { message = "^refactor", group = "Refactoring" },
    { message = "^chore", group = "Chores" },
    { message = "^ci", group = "CI" },
    { message = "^test", group = "Tests" },
    { message = "^perf", group = "Performance" },
]

[remote.github]
owner = "molofson"
repo = "now-playing"

[changelog]
header = """
# Changelog
"""
# One blank line *after* each group title
group = """
### {{ group }}

"""
# No blank lines between commits
body = """{% for commit in commits -%}
- {{ commit.message | trim }} ([{{ commit.id | truncate(end="7") }}](https://github.com/molofson/now-playing/commit/{{ commit.id }}))
{% endfor -%}"""
footer = ""

[preprocessors]
filter_commits = true
