# ./cliff.toml
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}

{% for commit in commits %}
- {{ commit.message | strip }} ([{{ commit.id | truncate(length=7, end="" }}]({{ commit.remote }}{{ commit.id }})
{% endfor %}

{% endfor %}
"""
footer = ""

[git]
tag_pattern = "v[0-9]*"
