# -----------------------------------------------------------------------------
# Code Coverage Workflow
#
# Runs pytest with coverage and uploads report to Codecov
# -----------------------------------------------------------------------------
name: Coverage

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -r requirements-dev.txt

      - name: Run tests
        run: make test

      - name: Generate coverage reports
        run: make coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }} # Only required for private repos
          fail_ci_if_error: true
